---
abstract: 'Japanese Municipals Data.'
author:
  - 'Yukio Suzuki <yukio at cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geography-JapaneseMunicipals
no_index:
  directory:
    - inc
    - t
requires:
  Encode: 0
  Geography::JapanesePrefectures: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
